# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1a6ad5d5bf4b708dfdc877c35c8252b52e0f95ae66dff7df596e686567f0a03e2734e1d9bb0c9399612fb40de94182482141be429ae932485b9853a81cdc341

test:
  secret_key_base: 6b8e1466cda61ab7293d3b70653220bac14b5be960295794902fc1916fb7b37a2391605650630e302da411565e2c65acf1c3aee2a05bf8501cc522e14aa86383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
